import {useEffect,useMemo,useState} from 'react'
import {Building2,Plus,MapPin,UserRound,Ruler,Boxes,Calculator,ShoppingCart,BookOpen,AlertTriangle,ArrowLeft,Trash2,Home,ChevronRight} from 'lucide-react'
type Room={id:string,name:string,length:number,width:number,height:number}
type Project={id:string,name:string,address:string,client:string,rooms:Room[],createdAt:string}
const KEY='stroitel-projects-v1'
const uid=()=>crypto.randomUUID?.()??Date.now().toString(36)+Math.random().toString(36).slice(2)
const load=():Project[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
const save=(p:Project[])=>localStorage.setItem(KEY,JSON.stringify(p))
const area=(r:Room)=>r.length*r.width
const walls=(r:Room)=>(2*(r.length+r.width))*r.height

export default function App(){
 const [projects,setProjects]=useState<Project[]>(load),[selected,setSelected]=useState<string|null>(null),[modal,setModal]=useState(false)
 useEffect(()=>save(projects),[projects])
 const project=projects.find(p=>p.id===selected)
 const addProject=(x:Omit<Project,'id'|'rooms'|'createdAt'>)=>{const p={...x,id:uid(),rooms:[],createdAt:new Date().toISOString()};setProjects(v=>[p,...v]);setSelected(p.id);setModal(false)}
 if(project)return <ProjectView project={project} onBack={()=>setSelected(null)} onAddRoom={r=>setProjects(v=>v.map(p=>p.id===project.id?{...p,rooms:[...p.rooms,{...r,id:uid()}]}:p))} onDelete={()=>{setProjects(v=>v.filter(p=>p.id!==project.id));setSelected(null)}}/>
 return <><HomeView projects={projects} onOpen={setSelected} onAdd={()=>setModal(true)}/>{modal&&<ProjectModal onClose={()=>setModal(false)} onSave={addProject}/>}</>
}
function HomeView({projects,onOpen,onAdd}:{projects:Project[],onOpen:(id:string)=>void,onAdd:()=>void}){return <div className="app"><header className="topbar"><div><div className="eyebrow">СТРОИТЕЛЬ</div><h1>Мои объекты</h1></div><button className="round" onClick={onAdd}><Plus/></button></header><main className="content"><section className="hero"><Building2 size={42}/><div><h2>Всё по объекту — в одном месте</h2><p>Замеры, материалы, смета, закупки и дневник работ.</p></div><button className="primary" onClick={onAdd}>Создать объект</button></section><div className="section-title"><h2>Объекты</h2><span>{projects.length}</span></div>{projects.length===0?<div className="empty"><Home size={34}/><b>Пока нет объектов</b><p>Создай первый объект и начни с замеров.</p></div>:<div className="cards">{projects.map(p=><button className="project-card" key={p.id} onClick={()=>onOpen(p.id)}><div className="project-icon"><Building2/></div><div className="card-main"><b>{p.name}</b><span>{p.address||'Адрес не указан'}</span><small>{p.rooms.length} помещений</small></div><ChevronRight/></button>)}</div>}</main><div className="hint">📱 В меню браузера можно добавить «Строитель» на главный экран.</div></div>}
function ProjectView({project,onBack,onAddRoom,onDelete}:{project:Project,onBack:()=>void,onAddRoom:(r:Omit<Room,'id'>)=>void,onDelete:()=>void}){
 const [roomModal,setRoomModal]=useState(false),floor=useMemo(()=>project.rooms.reduce((s,r)=>s+area(r),0),[project.rooms]),wall=useMemo(()=>project.rooms.reduce((s,r)=>s+walls(r),0),[project.rooms])
 const modules=[['Замеры',Ruler,'#e9f2ff'],['Материалы',Boxes,'#edf8f0'],['Смета',Calculator,'#fff4df'],['Закупки',ShoppingCart,'#f4ecff'],['Дневник',BookOpen,'#fff0f0'],['Проблемы',AlertTriangle,'#fff7d8']] as const
 return <div className="app"><header className="topbar detail"><button className="back" onClick={onBack}><ArrowLeft/></button><div><div className="eyebrow">ОБЪЕКТ</div><h1>{project.name}</h1></div><button className="more" onClick={()=>{if(confirm('Удалить объект?'))onDelete()}}><Trash2/></button></header><main className="content"><div className="project-info">{project.address&&<span><MapPin size={16}/>{project.address}</span>}{project.client&&<span><UserRound size={16}/>{project.client}</span>}</div><div className="stats"><div><b>{floor.toFixed(1)}</b><span>м² пола</span></div><div><b>{wall.toFixed(1)}</b><span>м² стен</span></div><div><b>{project.rooms.length}</b><span>помещений</span></div></div><div className="section-title"><h2>Разделы</h2></div><div className="modules">{modules.map(([name,Icon,bg])=><button className="module" key={name} onClick={()=>name==='Замеры'&&setRoomModal(true)} style={{'--bg':bg} as React.CSSProperties}><Icon/><b>{name}</b><ChevronRight/></button>)}</div><div className="section-title"><h2>Помещения</h2><button className="link" onClick={()=>setRoomModal(true)}>＋ Добавить</button></div>{project.rooms.length===0?<div className="empty compact"><Ruler size={30}/><b>Добавь первое помещение</b><p>Длина, ширина и высота — площади посчитаются автоматически.</p></div>:<div className="rooms">{project.rooms.map(r=><div className="room" key={r.id}><div><b>{r.name}</b><span>{r.length} × {r.width} × {r.height} м</span></div><strong>{area(r).toFixed(1)} м²</strong></div>)}</div>}</main>{roomModal&&<RoomModal onClose={()=>setRoomModal(false)} onSave={r=>{onAddRoom(r);setRoomModal(false)}}/>}</div>}
function RoomModal({onClose,onSave}:{onClose:()=>void,onSave:(r:Omit<Room,'id'>)=>void}){const [name,setName]=useState(''),[length,setLength]=useState(''),[width,setWidth]=useState(''),[height,setHeight]=useState('2.7'),ok=!!name.trim()&&+length>0&&+width>0&&+height>0;return <div className="overlay"><div className="modal"><div className="modal-head"><h2>Новое помещение</h2><button className="close" onClick={onClose}>×</button></div><label>Название<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Например, Кухня"/></label><div className="grid3"><label>Длина, м<input inputMode="decimal" value={length} onChange={e=>setLength(e.target.value)} placeholder="5"/></label><label>Ширина, м<input inputMode="decimal" value={width} onChange={e=>setWidth(e.target.value)} placeholder="4"/></label><label>Высота, м<input inputMode="decimal" value={height} onChange={e=>setHeight(e.target.value)}/></label></div><div className="calc-preview">Площадь пола: <b>{(+length||0)*(+width||0)?((+length||0)*(+width||0)).toFixed(1):'0.0'} м²</b></div><div className="actions"><button className="secondary" onClick={onClose}>Отмена</button><button className="primary" disabled={!ok} onClick={()=>onSave({name:name.trim(),length:+length,width:+width,height:+height})}>Сохранить</button></div></div></div>}
function ProjectModal({onClose,onSave}:{onClose:()=>void,onSave:(p:Omit<Project,'id'|'rooms'|'createdAt'>)=>void}){const [name,setName]=useState(''),[address,setAddress]=useState(''),[client,setClient]=useState('');return <div className="overlay"><div className="modal"><div className="modal-head"><h2>Новый объект</h2><button className="close" onClick={onClose}>×</button></div><label>Название объекта<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Дом Иванова"/></label><label>Адрес<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Город, улица"/></label><label>Заказчик<input value={client} onChange={e=>setClient(e.target.value)} placeholder="Имя заказчика"/></label><div className="actions"><button className="secondary" onClick={onClose}>Отмена</button><button className="primary" disabled={!name.trim()} onClick={()=>onSave({name:name.trim(),address,client})}>Создать</button></div></div></div>}
