export type MaterialSpec={name:string;unit:string;packageSize:number;packageUnit:string;waste:number;price:number;priceIsEstimate:true}

export const MATERIAL_CATALOG:MaterialSpec[]=[
{name:'Сухая смесь для стяжки',unit:'кг',packageSize:25,packageUnit:'мешок',waste:5,price:18,priceIsEstimate:true},
{name:'Штукатурная смесь',unit:'кг',packageSize:30,packageUnit:'мешок',waste:5,price:17.33,priceIsEstimate:true},
{name:'Шпаклёвка',unit:'кг',packageSize:20,packageUnit:'мешок',waste:5,price:42.5,priceIsEstimate:true},
{name:'Грунтовка',unit:'л',packageSize:10,packageUnit:'канистра',waste:5,price:120,priceIsEstimate:true},
{name:'Краска',unit:'л',packageSize:10,packageUnit:'ведро',waste:5,price:240,priceIsEstimate:true},
{name:'Плитка',unit:'м²',packageSize:1.44,packageUnit:'коробка',waste:10,price:1800,priceIsEstimate:true},
{name:'Плиточный клей',unit:'кг',packageSize:25,packageUnit:'мешок',waste:5,price:28,priceIsEstimate:true},

{name:'Песок',unit:'т',packageSize:1,packageUnit:'т',waste:5,price:1800,priceIsEstimate:true},
{name:'Щебень',unit:'т',packageSize:1,packageUnit:'т',waste:5,price:2600,priceIsEstimate:true},
{name:'Геотекстиль',unit:'м²',packageSize:50,packageUnit:'рулон',waste:10,price:45,priceIsEstimate:true},
{name:'Грунт обратной засыпки',unit:'м³',packageSize:1,packageUnit:'м³',waste:5,price:800,priceIsEstimate:true},
{name:'Бетон',unit:'м³',packageSize:1,packageUnit:'м³',waste:5,price:6500,priceIsEstimate:true},
{name:'Арматура',unit:'кг',packageSize:1,packageUnit:'кг',waste:5,price:75,priceIsEstimate:true},
{name:'Вязальная проволока',unit:'кг',packageSize:5,packageUnit:'бухта',waste:5,price:180,priceIsEstimate:true},
{name:'Опалубочная доска',unit:'м²',packageSize:1,packageUnit:'м²',waste:10,price:650,priceIsEstimate:true},
{name:'Гидроизоляция фундамента',unit:'м²',packageSize:15,packageUnit:'рулон',waste:10,price:180,priceIsEstimate:true},
{name:'Утеплитель XPS',unit:'м²',packageSize:5.76,packageUnit:'упаковка',waste:5,price:650,priceIsEstimate:true},

{name:'Газоблок',unit:'м³',packageSize:1,packageUnit:'м³',waste:5,price:8500,priceIsEstimate:true},
{name:'Клей для газоблока',unit:'кг',packageSize:25,packageUnit:'мешок',waste:5,price:24,priceIsEstimate:true},
{name:'Пеноблок',unit:'м³',packageSize:1,packageUnit:'м³',waste:5,price:7200,priceIsEstimate:true},
{name:'Кирпич',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:5,price:28,priceIsEstimate:true},
{name:'Кладочный раствор',unit:'кг',packageSize:25,packageUnit:'мешок',waste:5,price:12,priceIsEstimate:true},
{name:'Камень',unit:'м²',packageSize:1,packageUnit:'м²',waste:5,price:1800,priceIsEstimate:true},
{name:'Сетка кладочная',unit:'м²',packageSize:20,packageUnit:'рулон',waste:5,price:90,priceIsEstimate:true},

{name:'Профильная труба',unit:'м',packageSize:6,packageUnit:'шт.',waste:5,price:450,priceIsEstimate:true},
{name:'Металлический профиль',unit:'м',packageSize:3,packageUnit:'шт.',waste:5,price:250,priceIsEstimate:true},
{name:'Уголок металлический',unit:'м',packageSize:6,packageUnit:'шт.',waste:5,price:350,priceIsEstimate:true},
{name:'Электроды',unit:'кг',packageSize:5,packageUnit:'пачка',waste:5,price:320,priceIsEstimate:true},
{name:'Отрезной диск',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:10,price:150,priceIsEstimate:true},
{name:'Грунт по металлу',unit:'кг',packageSize:20,packageUnit:'ведро',waste:5,price:260,priceIsEstimate:true},
{name:'Краска по металлу',unit:'кг',packageSize:20,packageUnit:'ведро',waste:5,price:320,priceIsEstimate:true},

{name:'Доска строительная',unit:'м³',packageSize:1,packageUnit:'м³',waste:10,price:18000,priceIsEstimate:true},
{name:'Брус',unit:'м³',packageSize:1,packageUnit:'м³',waste:10,price:22000,priceIsEstimate:true},
{name:'Крепёж строительный',unit:'кг',packageSize:5,packageUnit:'коробка',waste:5,price:250,priceIsEstimate:true},
{name:'Анкер',unit:'шт.',packageSize:10,packageUnit:'упаковка',waste:5,price:120,priceIsEstimate:true},
{name:'Деревозащитная пропитка',unit:'л',packageSize:10,packageUnit:'канистра',waste:5,price:280,priceIsEstimate:true},

{name:'OSB-3',unit:'м²',packageSize:3.125,packageUnit:'лист',waste:10,price:900,priceIsEstimate:true},
{name:'Подкладочный ковёр',unit:'м²',packageSize:15,packageUnit:'рулон',waste:10,price:120,priceIsEstimate:true},
{name:'Гибкая черепица',unit:'м²',packageSize:3,packageUnit:'упаковка',waste:10,price:650,priceIsEstimate:true},
{name:'Композитная черепица',unit:'м²',packageSize:2,packageUnit:'упаковка',waste:10,price:1500,priceIsEstimate:true},
{name:'Керамическая черепица',unit:'м²',packageSize:1,packageUnit:'м²',waste:10,price:1900,priceIsEstimate:true},
{name:'Цементно-песчаная черепица',unit:'м²',packageSize:1,packageUnit:'м²',waste:10,price:1200,priceIsEstimate:true},
{name:'Ондулин',unit:'м²',packageSize:1.9,packageUnit:'лист',waste:10,price:850,priceIsEstimate:true},
{name:'Шифер',unit:'м²',packageSize:1.75,packageUnit:'лист',waste:10,price:650,priceIsEstimate:true},
{name:'Кровельная мембрана',unit:'м²',packageSize:75,packageUnit:'рулон',waste:10,price:90,priceIsEstimate:true},
{name:'Рулонная кровля',unit:'м²',packageSize:10,packageUnit:'рулон',waste:10,price:250,priceIsEstimate:true},
{name:'Профнастил',unit:'м²',packageSize:1,packageUnit:'м²',waste:10,price:900,priceIsEstimate:true},
{name:'Металлочерепица',unit:'м²',packageSize:1,packageUnit:'м²',waste:10,price:1000,priceIsEstimate:true},
{name:'Крепёж кровельный',unit:'шт.',packageSize:250,packageUnit:'упаковка',waste:5,price:8,priceIsEstimate:true},
{name:'Планка кровельная',unit:'м',packageSize:2,packageUnit:'шт.',waste:5,price:300,priceIsEstimate:true},
{name:'Утеплитель минеральный',unit:'м²',packageSize:5.76,packageUnit:'упаковка',waste:5,price:650,priceIsEstimate:true},
{name:'Пароизоляционная плёнка',unit:'м²',packageSize:75,packageUnit:'рулон',waste:10,price:55,priceIsEstimate:true},
{name:'Кровельная гидроизоляция',unit:'м²',packageSize:75,packageUnit:'рулон',waste:10,price:55,priceIsEstimate:true},

{name:'Фасадный утеплитель',unit:'м²',packageSize:5.76,packageUnit:'упаковка',waste:5,price:750,priceIsEstimate:true},
{name:'Фасадный клей',unit:'кг',packageSize:25,packageUnit:'мешок',waste:5,price:30,priceIsEstimate:true},
{name:'Фасадная сетка',unit:'м²',packageSize:50,packageUnit:'рулон',waste:5,price:90,priceIsEstimate:true},
{name:'Дюбель фасадный',unit:'шт.',packageSize:100,packageUnit:'упаковка',waste:5,price:18,priceIsEstimate:true},
{name:'Фасадная грунтовка',unit:'л',packageSize:10,packageUnit:'канистра',waste:5,price:140,priceIsEstimate:true},
{name:'Фасадная штукатурка',unit:'кг',packageSize:25,packageUnit:'мешок',waste:5,price:65,priceIsEstimate:true},
{name:'Сайдинг',unit:'м²',packageSize:10,packageUnit:'упаковка',waste:10,price:650,priceIsEstimate:true},

{name:'Гипсокартон',unit:'м²',packageSize:3,packageUnit:'лист',waste:10,price:550,priceIsEstimate:true},
{name:'Профиль ГКЛ',unit:'м',packageSize:3,packageUnit:'шт.',waste:5,price:180,priceIsEstimate:true},
{name:'Саморез по ГКЛ',unit:'шт.',packageSize:1000,packageUnit:'упаковка',waste:5,price:1.5,priceIsEstimate:true},
{name:'Армирующая лента',unit:'м',packageSize:45,packageUnit:'рулон',waste:5,price:25,priceIsEstimate:true},
{name:'Клей для обоев',unit:'кг',packageSize:0.5,packageUnit:'пачка',waste:5,price:300,priceIsEstimate:true},
{name:'Обои',unit:'м²',packageSize:5.3,packageUnit:'рулон',waste:10,price:450,priceIsEstimate:true},

{name:'Подложка под ламинат',unit:'м²',packageSize:10,packageUnit:'упаковка',waste:5,price:100,priceIsEstimate:true},
{name:'Ламинат',unit:'м²',packageSize:2.2,packageUnit:'упаковка',waste:10,price:900,priceIsEstimate:true},
{name:'Линолеум',unit:'м²',packageSize:1,packageUnit:'м²',waste:10,price:750,priceIsEstimate:true},
{name:'Кварцвинил',unit:'м²',packageSize:2.2,packageUnit:'упаковка',waste:10,price:1800,priceIsEstimate:true},
{name:'Паркет',unit:'м²',packageSize:1.5,packageUnit:'упаковка',waste:10,price:2500,priceIsEstimate:true},
{name:'Плинтус',unit:'м',packageSize:2.5,packageUnit:'шт.',waste:5,price:180,priceIsEstimate:true},
{name:'Затирка',unit:'кг',packageSize:2,packageUnit:'пачка',waste:5,price:180,priceIsEstimate:true},
{name:'Наливной пол',unit:'кг',packageSize:20,packageUnit:'мешок',waste:5,price:40,priceIsEstimate:true},

{name:'Кабель силовой',unit:'м',packageSize:100,packageUnit:'бухта',waste:5,price:120,priceIsEstimate:true},
{name:'Гофра',unit:'м',packageSize:100,packageUnit:'бухта',waste:5,price:35,priceIsEstimate:true},
{name:'Подрозетник',unit:'шт.',packageSize:10,packageUnit:'упаковка',waste:5,price:80,priceIsEstimate:true},
{name:'Розетка',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:5,price:450,priceIsEstimate:true},
{name:'Выключатель',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:5,price:400,priceIsEstimate:true},
{name:'Светильник',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:5,price:1500,priceIsEstimate:true},
{name:'Электрощит',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:4500,priceIsEstimate:true},
{name:'Автомат защиты',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:500,priceIsEstimate:true},
{name:'УЗО/дифавтомат',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:1800,priceIsEstimate:true},
{name:'Комплект заземления',unit:'компл.',packageSize:1,packageUnit:'компл.',waste:0,price:6000,priceIsEstimate:true},

{name:'Труба водоснабжения',unit:'м',packageSize:10,packageUnit:'бухта',waste:5,price:180,priceIsEstimate:true},
{name:'Фитинги водоснабжения',unit:'шт.',packageSize:10,packageUnit:'упаковка',waste:5,price:180,priceIsEstimate:true},
{name:'Кран шаровый',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:600,priceIsEstimate:true},
{name:'Коллектор',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:3500,priceIsEstimate:true},
{name:'Канализационная труба',unit:'м',packageSize:1,packageUnit:'шт.',waste:5,price:350,priceIsEstimate:true},
{name:'Сифон',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:650,priceIsEstimate:true},
{name:'Монтажная пена',unit:'шт.',packageSize:1,packageUnit:'баллон',waste:10,price:550,priceIsEstimate:true},

{name:'Труба отопления',unit:'м',packageSize:10,packageUnit:'бухта',waste:5,price:220,priceIsEstimate:true},
{name:'Радиатор',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:6000,priceIsEstimate:true},
{name:'Труба тёплого пола',unit:'м',packageSize:200,packageUnit:'бухта',waste:5,price:110,priceIsEstimate:true},
{name:'Теплоизоляция труб',unit:'м',packageSize:10,packageUnit:'упаковка',waste:5,price:80,priceIsEstimate:true},
{name:'Воздуховод',unit:'м',packageSize:1,packageUnit:'шт.',waste:5,price:700,priceIsEstimate:true},
{name:'Фасонные элементы вентиляции',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:5,price:900,priceIsEstimate:true},
{name:'Вентиляционная решётка',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:500,priceIsEstimate:true},

{name:'Дренажная труба',unit:'м',packageSize:50,packageUnit:'бухта',waste:5,price:250,priceIsEstimate:true},
{name:'Труба наружной канализации',unit:'м',packageSize:1,packageUnit:'шт.',waste:5,price:500,priceIsEstimate:true},
{name:'Колодец дренажный',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:8000,priceIsEstimate:true},
{name:'Септик',unit:'шт.',packageSize:1,packageUnit:'комплект',waste:0,price:65000,priceIsEstimate:true},

{name:'Оконный блок',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:25000,priceIsEstimate:true},
{name:'Дверной блок',unit:'шт.',packageSize:1,packageUnit:'шт.',waste:0,price:18000,priceIsEstimate:true},
{name:'Подоконник',unit:'м',packageSize:1,packageUnit:'м',waste:5,price:1000,priceIsEstimate:true},
{name:'Анкер для окон',unit:'шт.',packageSize:50,packageUnit:'упаковка',waste:5,price:35,priceIsEstimate:true},

{name:'Мешок строительный',unit:'шт.',packageSize:50,packageUnit:'упаковка',waste:10,price:25,priceIsEstimate:true},
{name:'Расходники для демонтажа',unit:'компл.',packageSize:1,packageUnit:'компл.',waste:10,price:1000,priceIsEstimate:true},
{name:'Контейнер/вывоз отходов',unit:'рейс',packageSize:1,packageUnit:'рейс',waste:0,price:8000,priceIsEstimate:true},

{name:'Бордюр',unit:'м',packageSize:1,packageUnit:'шт.',waste:5,price:500,priceIsEstimate:true},
{name:'Цемент',unit:'кг',packageSize:25,packageUnit:'мешок',waste:5,price:18,priceIsEstimate:true},
{name:'Тротуарная плитка',unit:'м²',packageSize:0.96,packageUnit:'упаковка',waste:10,price:1200,priceIsEstimate:true}
]

export const getMaterialSpec=(name:string,unit:string)=>MATERIAL_CATALOG.find(x=>x.name===name&&x.unit===unit)

export const purchaseQty=(qty:number,spec?:MaterialSpec)=>spec&&spec.packageSize>0?{packages:Math.ceil(qty/spec.packageSize),purchaseQty:Math.ceil(qty/spec.packageSize)*spec.packageSize}:{packages:0,purchaseQty:qty}
