import {useEffect,useMemo,useState} from 'react'
import {LocateFixed,RefreshCw,Store,ExternalLink,Search,Navigation} from 'lucide-react'
type Material={id:string,name:string,unit:string,qty:number,price:number,bought:boolean}
type StoreItem={id:string,name:string,address:string,lat:number,lon:number}
const cityName=(data:any)=>data?.city||data?.locality||data?.principalSubdivision||'Ваш город'
const distance=(a:number,b:number,c:number,d:number)=>{const R=6371,rad=Math.PI/180,x=(c-a)*rad,y=(d-b)*rad,h=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
export default function PriceFinder({materials}:{materials:Material[]}){
 const [coords,setCoords]=useState<{lat:number,lon:number}|null>(null),[city,setCity]=useState(''),[stores,setStores]=useState<StoreItem[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[radius,setRadius]=useState('25')
 const locate=()=>{setError('');if(!navigator.geolocation){setError('Браузер не поддерживает определение местоположения.');return}setLoading(true);navigator.geolocation.getCurrentPosition(async p=>{try{const lat=p.coords.latitude,lon=p.coords.longitude;setCoords({lat,lon});const geo=await fetch('https://api.bigdatacloud.net/data/reverse-geocode-client?latitude='+lat+'&longitude='+lon+'&localityLanguage=ru');const gd=await geo.json();setCity(cityName(gd));const r=Math.min(50,Math.max(2,+radius||25))*1000;const query='[out:json][timeout:20];(nwr[shop~"^(doityourself|hardware|trade|building_materials)$"](around:'+r+','+lat+','+lon+');nwr[craft~"^(building|carpenter)$"](around:'+r+','+lat+','+lon+'););out center;';const over=await fetch('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(query));if(!over.ok)throw new Error('Не удалось получить магазины');const json=await over.json();const list:StoreItem[]=(json.elements||[]).map((x:any)=>({id:String(x.id),name:x.tags?.name||x.tags?.['name:ru']||'Строительный магазин',address:[x.tags?.['addr:street'],x.tags?.['addr:housenumber']].filter(Boolean).join(', ')||'Адрес не указан',lat:x.lat??x.center?.lat,lon:x.lon??x.center?.lon})).filter((x:StoreItem)=>Number.isFinite(x.lat)&&Number.isFinite(x.lon));list.sort((a,b)=>distance(lat,lon,a.lat,a.lon)-distance(lat,lon,b.lat,b.lon));setStores(list.slice(0,30))}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить поиск')}finally{setLoading(false)}},()=>{setError('Доступ к местоположению запрещён. Разреши геолокацию для сайта и повтори.');setLoading(false)},{enableHighAccuracy:false,timeout:12000,maximumAge:300000})}
 useEffect(()=>{locate()},[])
 const searchUrl=(material:string,store?:string)=>'https://www.google.com/search?q='+encodeURIComponent([material,store,city,'цена'].filter(Boolean).join(' '))
 const yandexUrl=(material:string,store?:string)=>'https://yandex.ru/search/?text='+encodeURIComponent([material,store,city,'цена'].filter(Boolean).join(' '))
 const materialRows=useMemo(()=>materials.filter(m=>m.name.trim()),[materials])
 return <section className="price-finder"><div className="section-title"><div><h2>Цены и магазины</h2><span>Ищем строительные магазины рядом с объектом.</span></div><button className="link" onClick={locate} disabled={loading}><RefreshCw size={15}/> Обновить</button></div><div className="location-card"><div className="location-main"><LocateFixed size={22}/><div><b>{city||'Определяем город…'}</b><span>{coords?'Местоположение получено · радиус '+radius+' км':'Нужно разрешение браузера'}</span></div></div><div className="location-actions"><label>Радиус<select value={radius} onChange={e=>setRadius(e.target.value)}><option value="5">5 км</option><option value="10">10 км</option><option value="25">25 км</option><option value="50">50 км</option></select></label><button className="primary" onClick={locate} disabled={loading}>{loading?'Ищем…':'Найти магазины'}</button></div></div>{error&&<div className="info-box">{error}</div>}{stores.length>0&&<div className="store-list">{stores.map(s=><article className="store-card" key={s.id}><div className="store-icon"><Store size={20}/></div><div><b>{s.name}</b><span>{s.address}</span>{coords&&<small>{distance(coords.lat,coords.lon,s.lat,s.lon).toFixed(1)} км</small>}</div><a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(s.lat+','+s.lon)} target="_blank" rel="noreferrer"><Navigation size={16}/></a></article>)}</div>}<div className="section-title price-heading"><div><h2>Поиск цен на материалы</h2><span>Выбирай материал из расчёта и открывай цены по своему городу.</span></div><Search size={20}/></div>{materialRows.length===0?<div className="empty compact"><b>Пока нет рассчитанных материалов</b><p>Добавь работу и получи список материалов.</p></div>:<div className="price-list">{materialRows.map(m=><div className="price-row" key={m.id}><div><b>{m.name}</b><span>Нужно: {m.qty.toFixed(1)} {m.unit}</span></div><div className="price-actions"><a href={searchUrl(m.name)} target="_blank" rel="noreferrer">Google <ExternalLink size={13}/></a><a href={yandexUrl(m.name)} target="_blank" rel="noreferrer">Яндекс <ExternalLink size={13}/></a></div></div>)}</div>}{stores.length>0&&materialRows.length>0&&<div className="store-search-box"><b>Искать материал в найденном магазине</b><div>{materialRows.slice(0,8).map(m=><a key={m.id} href={searchUrl(m.name,stores[0].name)} target="_blank" rel="noreferrer">{m.name}</a>)}</div></div>}</section>
}