import {useState} from 'react'
import {LocateFixed,RefreshCw,Store,Navigation,Search} from 'lucide-react'
type Material={id:string,name:string,unit:string,qty:number,price:number,bought:boolean}
type StoreItem={id:string,name:string,address:string,lat:number,lon:number}
const distance=(a:number,b:number,c:number,d:number)=>{const R=6371,rad=Math.PI/180,x=(c-a)*rad,y=(d-b)*rad,h=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return R*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
export default function PriceFinder({materials}:{materials:Material[]}){const [city,setCity]=useState(''),[coords,setCoords]=useState<{lat:number,lon:number}|null>(null),[stores,setStores]=useState<StoreItem[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
const locate=()=>{setLoading(true);setError('');if(!navigator.geolocation){setError('Геолокация недоступна');setLoading(false);return}navigator.geolocation.getCurrentPosition(async p=>{try{const lat=p.coords.latitude,lon=p.coords.longitude;setCoords({lat,lon});const g=await fetch('https://api.bigdatacloud.net/data/reverse-geocode-client?latitude='+lat+'&longitude='+lon+'&localityLanguage=ru');const d=await g.json();setCity(d.city||d.locality||d.principalSubdivision||'Ваш город');const q='[out:json][timeout:20];nwr[shop](around:25000,'+lat+','+lon+');out center;';const r=await fetch('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q));const j=await r.json();const a=(j.elements||[]).map((x:any)=>({id:String(x.id),name:x.tags?.name||'Строительный магазин',address:[x.tags?.['addr:street'],x.tags?.['addr:housenumber']].filter(Boolean).join(', ')||'Адрес не указан',lat:x.lat??x.center?.lat,lon:x.lon??x.center?.lon})).filter((x:StoreItem)=>x.name&&Number.isFinite(x.lat)&&Number.isFinite(x.lon));a.sort((x:StoreItem,y:StoreItem)=>distance(lat,lon,x.lat,x.lon)-distance(lat,lon,y.lat,y.lon));setStores(a.slice(0,20))}catch(e){setError(e instanceof Error?e.message:'Не удалось выполнить поиск')}finally{setLoading(false)}},()=>{setError('Разреши доступ к геолокации браузеру');setLoading(false)},{timeout:12000,maximumAge:300000})}
const search=(m:string)=>'https://www.google.com/search?q='+encodeURIComponent(m+' '+city+' цена строительный магазин')
return <section className="price-finder"><div className="section-title"><div><h2>Цены и магазины</h2><span>Город и ближайшие магазины определяются по телефону.</span></div><button className="link" onClick={locate} disabled={loading}><RefreshCw size={15}/> {loading?'Ищем…':'Обновить'}</button></div><div className="location-card"><div className="location-main"><LocateFixed size={22}/><div><b>{city||'Город ещё не определён'}</b><span>{coords?'Местоположение получено':'Нужно разрешение браузера'}</span></div></div><button className="primary" onClick={locate} disabled={loading}>{loading?'Поиск…':'Определить и найти'}</button></div>{error&&<div className="info-box">{error}</div>}{stores.length>0&&<div className="store-list">{stores.map(s=><article className="store-card" key={s.id}><Store size={20}/><div><b>{s.name}</b><span>{s.address}</span><small>{coords&&distance(coords.lat,coords.lon,s.lat,s.lon).toFixed(1)+' км'}</small></div><a href={'https://www.google.com/maps/search/?api=1&query='+s.lat+','+s.lon} target="_blank" rel="noreferrer"><Navigation size={16}/></a></article>)}</div>}<div className="section-title"><div><h2>Цены на рассчитанные материалы</h2><span>Пока открываем поиск актуальных предложений по вашему городу.</span></div><Search size={20}/></div>{materials.length===0?<div className="empty compact"><b>Материалов пока нет</b><p>Сначала рассчитай материалы в разделе «Работы».</p></div>:<div className="price-list">{materials.map(m=><div className="price-row" key={m.id}><div><b>{m.name}</b><span>Нужно: {m.qty.toFixed(1)} {m.unit}</span></div><a href={search(m.name)} target="_blank" rel="noreferrer">Найти цену</a></div>)}</div>}</section>}
